# Generated by Django 2.0 on 2018-01-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('time_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
