# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_manager', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='time_manager.Project'),
        ),
    ]
